# create your drupal and postgres config here, based off the last assignment
services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-drupal
    ports:
      - 8080:80
    volumes:
      - drupal-data:/var/lib/postgresql/data

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123456789

volumes:
  drupal-data: